"use server";

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { checkPlan } from "@/lib/plan";

type ExportFormat = "markdown" | "plaintext" | "cursorrules";

export async function generateContext(
  projectId: string,
  format: ExportFormat = "markdown"
) {
  const session = await auth();
  if (!session?.user?.id) {
    return { error: "Not authenticated" };
  }

  const plan = await checkPlan(session.user.id);
  if (!plan.isPro) {
    return { error: "Pro plan required for AI context generation" };
  }

  const project = await db.project.findFirst({
    where: { id: projectId, userId: session.user.id },
    include: {
      notes: { orderBy: { updatedAt: "desc" } },
    },
  });

  if (!project) {
    return { error: "Project not found" };
  }

  const adrs = project.notes.filter((n) => n.type === "ADR");
  const prompts = project.notes.filter((n) => n.type === "PROMPT");
  const generalNotes = project.notes.filter((n) => n.type === "GENERAL");

  // Build context based on format
  let content = "";
  const totalTokens = Math.ceil(
    project.notes.reduce((sum, n) => sum + n.content.length, 0) / 4
  );

  if (format === "cursorrules") {
    content = buildCursorRules(project, adrs, prompts, generalNotes);
  } else if (format === "plaintext") {
    content = buildPlaintext(project, adrs, prompts, generalNotes);
  } else {
    content = buildMarkdown(project, adrs, prompts, generalNotes);
  }

  return { content, format, tokenEstimate: totalTokens };
}

function buildMarkdown(
  project: { name: string; description: string | null; stack: string[] },
  adrs: { title: string; content: string }[],
  prompts: { title: string; content: string }[],
  notes: { title: string; content: string }[]
) {
  const sections: string[] = [];

  sections.push(`# ${project.name} — Project Context`);
  if (project.description) {
    sections.push(`\n${project.description}`);
  }
  if (project.stack.length > 0) {
    sections.push(`\n**Tech stack:** ${project.stack.join(", ")}`);
  }

  if (adrs.length > 0) {
    sections.push("\n## Architecture decisions\n");
    for (const adr of adrs) {
      sections.push(`### ${adr.title}\n\n${adr.content}\n`);
    }
  }

  if (prompts.length > 0) {
    sections.push("\n## Saved prompts\n");
    for (const p of prompts) {
      sections.push(`### ${p.title}\n\n${p.content}\n`);
    }
  }

  if (notes.length > 0) {
    sections.push("\n## Notes\n");
    for (const n of notes) {
      sections.push(`### ${n.title}\n\n${n.content}\n`);
    }
  }

  return sections.join("\n");
}

function buildPlaintext(
  project: { name: string; description: string | null; stack: string[] },
  adrs: { title: string; content: string }[],
  prompts: { title: string; content: string }[],
  notes: { title: string; content: string }[]
) {
  const lines: string[] = [];

  lines.push(`PROJECT: ${project.name}`);
  if (project.description) lines.push(project.description);
  if (project.stack.length > 0) lines.push(`Stack: ${project.stack.join(", ")}`);
  lines.push("");

  if (adrs.length > 0) {
    lines.push("=== ARCHITECTURE DECISIONS ===\n");
    for (const adr of adrs) {
      lines.push(`--- ${adr.title} ---`);
      lines.push(adr.content);
      lines.push("");
    }
  }

  if (prompts.length > 0) {
    lines.push("=== PROMPTS ===\n");
    for (const p of prompts) {
      lines.push(`--- ${p.title} ---`);
      lines.push(p.content);
      lines.push("");
    }
  }

  if (notes.length > 0) {
    lines.push("=== NOTES ===\n");
    for (const n of notes) {
      lines.push(`--- ${n.title} ---`);
      lines.push(n.content);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function buildCursorRules(
  project: { name: string; description: string | null; stack: string[] },
  adrs: { title: string; content: string }[],
  prompts: { title: string; content: string }[],
  notes: { title: string; content: string }[]
) {
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  if (project.description) lines.push(`\n${project.description}`);
  lines.push(`\n## Tech Stack\n${project.stack.join(", ")}`);

  if (adrs.length > 0) {
    lines.push("\n## Architecture Decisions");
    for (const adr of adrs) {
      lines.push(`\n### ${adr.title}`);
      lines.push(adr.content);
    }
  }

  if (prompts.length > 0) {
    lines.push("\n## Development Guidelines");
    for (const p of prompts) {
      lines.push(`\n### ${p.title}`);
      lines.push(p.content);
    }
  }

  if (notes.length > 0) {
    lines.push("\n## Additional Context");
    for (const n of notes) {
      lines.push(`\n### ${n.title}`);
      lines.push(n.content);
    }
  }

  lines.push(
    "\n---\n*Generated by TrackFlow — project brain context export*"
  );

  return lines.join("\n");
}
